import { useState, type FormEvent } from 'react';
import { Check, LogOut, Pencil, Plus, Save, ShieldCheck, Trash2, X } from 'lucide-react';
import { getProjects, saveProjects, useProjects } from '../data/projectStore';
import type { Project, ProjectStatus } from '../types/project';
import { Seo } from '../components/Seo';

const PASSWORD_KEY = 'acs-admin-password'; const SESSION_KEY = 'acs-admin-session';
const statuses: ProjectStatus[] = ['Em produção','Projeto ativo','Em desenvolvimento','Projeto concluído','Protótipo'];
async function hash(value:string){const bytes=new TextEncoder().encode(value);const digest=await crypto.subtle.digest('SHA-256',bytes);return Array.from(new Uint8Array(digest)).map(byte=>byte.toString(16).padStart(2,'0')).join('')}
const blank:Project={slug:'',name:'',eyebrow:'',category:[],summary:'',problem:'',idea:'',solution:'',features:[],technologies:[],result:'',status:'Em desenvolvimento',featured:false,tone:'#60e6bd'};

export default function Admin(){
  const projects=useProjects(); const hasPassword=Boolean(localStorage.getItem(PASSWORD_KEY));
  const [authenticated,setAuthenticated]=useState(()=>sessionStorage.getItem(SESSION_KEY)==='true'); const [password,setPassword]=useState(''); const [confirm,setConfirm]=useState(''); const [error,setError]=useState(''); const [editing,setEditing]=useState<Project|null>(null); const [notice,setNotice]=useState('');
  async function access(event:FormEvent){event.preventDefault();setError('');if(!hasPassword){if(password.length<8)return setError('Use pelo menos 8 caracteres.');if(password!==confirm)return setError('As senhas não coincidem.');localStorage.setItem(PASSWORD_KEY,await hash(password))}else if(await hash(password)!==localStorage.getItem(PASSWORD_KEY))return setError('Senha incorreta.');sessionStorage.setItem(SESSION_KEY,'true');setAuthenticated(true);setPassword('');setConfirm('')}
  function remove(slug:string){if(!window.confirm('Excluir este projeto?'))return;saveProjects(getProjects().filter(item=>item.slug!==slug));setNotice('Projeto excluído.')}
  function persist(project:Project){const normalized={...project,slug:project.slug.trim().toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'')};const current=getProjects();const existing=current.findIndex(item=>item.slug===normalized.slug);saveProjects(existing>=0?current.map((item,index)=>index===existing?normalized:item):[...current,normalized]);setEditing(null);setNotice('Projeto salvo e publicado neste navegador.')}
  if(!authenticated)return <><Seo title="Área administrativa" description="Acesso administrativo ACS Tecnologia."/><section className="admin-login"><form onSubmit={access} className="admin-auth-card"><span className="admin-lock"><ShieldCheck/></span><span className="kicker">Área administrativa</span><h1>{hasPassword?'Acesse o conteúdo.':'Crie sua senha.'}</h1><p>{hasPassword?'Digite sua senha para gerenciar os projetos do site.':'Este é o primeiro acesso. Defina uma senha com pelo menos 8 caracteres.'}</p><label>Senha<input autoFocus type="password" value={password} onChange={e=>setPassword(e.target.value)} required minLength={8}/></label>{!hasPassword&&<label>Confirmar senha<input type="password" value={confirm} onChange={e=>setConfirm(e.target.value)} required minLength={8}/></label>}{error&&<p className="form-error" role="alert">{error}</p>}<button className="button" type="submit">{hasPassword?'Entrar':'Criar acesso'} <ShieldCheck size={17}/></button></form></section></>;
  return <><Seo title="Gerenciar conteúdo" description="Painel administrativo ACS Tecnologia."/><section className="admin-page"><header className="admin-heading"><div><span className="kicker">Conteúdo do site</span><h1>Projetos</h1><p>Cadastre e atualize o portfólio publicado.</p></div><div className="admin-actions"><button className="button" onClick={()=>setEditing({...blank})}><Plus size={17}/> Novo projeto</button><button className="button button-ghost" onClick={()=>{sessionStorage.removeItem(SESSION_KEY);setAuthenticated(false)}}><LogOut size={17}/> Sair</button></div></header>{notice&&<div className="admin-notice"><Check size={17}/>{notice}<button aria-label="Fechar aviso" onClick={()=>setNotice('')}><X size={16}/></button></div>}<div className="admin-projects">{projects.map(project=><article key={project.slug}><i style={{background:project.tone}}/><div><small>{project.eyebrow}</small><h2>{project.name}</h2><p>{project.summary}</p></div><div className="admin-row-actions"><button className="icon-button" aria-label={`Editar ${project.name}`} onClick={()=>setEditing({...project})}><Pencil/></button><button className="icon-button danger" aria-label={`Excluir ${project.name}`} onClick={()=>remove(project.slug)}><Trash2/></button></div></article>)}</div></section>{editing&&<ProjectEditor project={editing} onClose={()=>setEditing(null)} onSave={persist}/>}</>}

function ProjectEditor({project,onClose,onSave}:{project:Project;onClose:()=>void;onSave:(project:Project)=>void}){const [form,setForm]=useState(project);const update=<K extends keyof Project>(key:K,value:Project[K])=>setForm(current=>({...current,[key]:value}));return <div className="editor-backdrop"><form className="project-editor" onSubmit={e=>{e.preventDefault();onSave(form)}}><header><div><span className="kicker">Editor de projeto</span><h2>{project.name||'Novo projeto'}</h2></div><button type="button" className="icon-button" aria-label="Fechar" onClick={onClose}><X/></button></header><div className="editor-grid"><label>Nome<input value={form.name} onChange={e=>{update('name',e.target.value);if(!project.slug)update('slug',e.target.value)}} required/></label><label>Endereço (slug)<input value={form.slug} onChange={e=>update('slug',e.target.value)} required/></label><label className="wide">Chamada curta<input value={form.eyebrow} onChange={e=>update('eyebrow',e.target.value)} required/></label><label className="wide">Resumo<textarea rows={3} value={form.summary} onChange={e=>update('summary',e.target.value)} required/></label>{(['problem','idea','solution','result'] as const).map(key=><label className="wide" key={key}>{({problem:'Problema',idea:'Ideia',solution:'Solução',result:'Resultado'})[key]}<textarea rows={3} value={form[key]} onChange={e=>update(key,e.target.value)} required/></label>)}{(['category','features','technologies'] as const).map(key=><label className="wide" key={key}>{({category:'Categorias',features:'Funcionalidades',technologies:'Tecnologias'})[key]} <small>— uma por linha</small><textarea rows={3} value={form[key].join('\n')} onChange={e=>update(key,e.target.value.split('\n').map(v=>v.trim()).filter(Boolean))}/></label>)}<label>Status<select value={form.status} onChange={e=>update('status',e.target.value as ProjectStatus)}>{statuses.map(status=><option key={status}>{status}</option>)}</select></label><label>Cor do projeto<input type="color" value={form.tone} onChange={e=>update('tone',e.target.value)}/></label><label className="check-field"><input type="checkbox" checked={form.featured} onChange={e=>update('featured',e.target.checked)}/> Exibir na página inicial</label></div><footer><button type="button" className="button button-ghost" onClick={onClose}>Cancelar</button><button className="button" type="submit"><Save size={17}/> Salvar e publicar</button></footer></form></div>}
