import { useCallback,useEffect,useState,type FormEvent } from 'react';
import { ArrowLeft,Building2,CheckCircle2,CreditCard,ExternalLink,KeyRound,LogOut,Plus,Trash2,UserRound,UsersRound,Wrench } from 'lucide-react';
import { Link } from 'react-router-dom';
import { Seo } from '../components/Seo';

type Establishment={id:string;name:string;system:string;url:string};
type Client={id:string;name:string;phone:string;personType:'pf'|'pj';document:string;establishments:Establishment[];active:boolean};
type Charge={id:string;clientId:string;description:string;amount:number;dueDate:string;status:string};
type RequestItem={id:string;clientId:string;title:string;details:string;status:string;createdAt:string};
const money=(cents:number)=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(cents/100);

export default function AdminClients(){
  const [authenticated,setAuthenticated]=useState<boolean|null>(null);
  const [clients,setClients]=useState<Client[]>([]); const [charges,setCharges]=useState<Charge[]>([]); const [requests,setRequests]=useState<RequestItem[]>([]);
  const [personType,setPersonType]=useState<'pf'|'pj'>('pf'); const [places,setPlaces]=useState([{name:'',system:'',url:''}]);
  const [message,setMessage]=useState(''); const [error,setError]=useState('');
  const load=useCallback(async()=>{try{const response=await fetch('/api/portal/admin',{credentials:'same-origin'});if(!response.ok){setAuthenticated(false);return false}const result=await response.json();setClients(result.clients||[]);setCharges(result.charges||[]);setRequests(result.requests||[]);setAuthenticated(true);setError('');return true}catch{setError('Não foi possível conectar ao servidor.');setAuthenticated(false);return false}},[]);
  useEffect(()=>{void load()},[load]);
  async function connect(event:FormEvent<HTMLFormElement>){event.preventDefault();setError('');const pin=new FormData(event.currentTarget).get('pin');const response=await fetch('/api/portal/admin-session',{method:'POST',credentials:'same-origin',headers:{'content-type':'application/json'},body:JSON.stringify({pin})});const result=await response.json().catch(()=>({error:'Servidor indisponível.'}));if(!response.ok)return setError(result.error||'PIN inválido.');await load()}
  async function logout(){await fetch('/api/portal/admin-session',{method:'DELETE',credentials:'same-origin'});setAuthenticated(false)}
  async function submit(event:FormEvent<HTMLFormElement>,action:'client'|'charge'){event.preventDefault();setError('');setMessage('');const form=new FormData(event.currentTarget);const body=action==='client'?{action,personType,name:form.get('name'),document:form.get('document'),phone:form.get('phone'),pin:form.get('pin'),establishments:personType==='pj'?places:[]}:{action,clientId:form.get('clientId'),description:form.get('description'),amount:form.get('amount'),dueDate:form.get('dueDate')};const response=await fetch('/api/portal/admin',{method:'POST',credentials:'same-origin',headers:{'content-type':'application/json'},body:JSON.stringify(body)});const result=await response.json().catch(()=>({error:`Erro do servidor (${response.status}).`}));if(!response.ok)return setError(result.error||'Não foi possível salvar.');event.currentTarget.reset();if(action==='client'){setPersonType('pf');setPlaces([{name:'',system:'',url:''}])}setMessage(action==='client'?'Cliente cadastrado.':'Cobrança emitida.');await load()}
  async function remove(type:'client'|'charge'|'request',id:string,clientId?:string){const labels={client:'este cliente e todos os dados vinculados',charge:'esta cobrança',request:'esta solicitação'};if(!window.confirm(`Excluir ${labels[type]}? Essa ação não poderá ser desfeita.`))return;const response=await fetch('/api/portal/admin',{method:'DELETE',credentials:'same-origin',headers:{'content-type':'application/json'},body:JSON.stringify({type,id,clientId})});const result=await response.json().catch(()=>({error:'Resposta inválida.'}));if(!response.ok)return setError(result.error||'Não foi possível excluir.');setMessage('Item excluído com sucesso.');await load()}
  const clientName=(id:string)=>clients.find(client=>client.id===id)?.name||'Cliente removido';

  if(authenticated===null)return <div className="page-loader">Verificando sessão…</div>;
  if(!authenticated)return <><Seo title="Gestão de clientes" description="Gestão segura do Portal do Cliente."/><section className="admin-login"><form className="admin-auth-card" onSubmit={connect}><span className="admin-lock"><KeyRound/></span><span className="kicker">Portal do Cliente</span><h1>Gestão financeira.</h1><p>Use seu PIN administrativo de 6 dígitos.</p><label>PIN administrativo<input name="pin" type="password" inputMode="numeric" pattern="[0-9]{6}" maxLength={6} autoFocus required/></label>{error&&<p className="form-error">{error}</p>}<button className="button">Acessar gestão</button></form></section></>;
  return <><Seo title="Clientes e cobranças" description="Gestão do Portal do Cliente."/><section className="admin-page">
    <Link className="back" to="/admin"><ArrowLeft/> Voltar aos projetos</Link>
    <header className="admin-heading"><div><span className="kicker">Portal do Cliente</span><h1>Clientes e cobranças</h1><p>Tudo que você cadastrar pode ser consultado e excluído aqui.</p></div><button className="button button-ghost" onClick={logout}><LogOut/> Sair</button></header>
    {message&&<div className="admin-notice"><CheckCircle2/>{message}</div>}{error&&<p className="admin-error" role="alert">{error}</p>}
    <div className="client-admin-grid">
      <form className="portal-card client-form" onSubmit={e=>submit(e,'client')}><span className="portal-icon"><UsersRound/></span><h2>Novo cliente</h2>
        <div className="client-type"><button type="button" className={personType==='pf'?'active':''} onClick={()=>setPersonType('pf')}><UserRound/> Pessoa física</button><button type="button" className={personType==='pj'?'active':''} onClick={()=>setPersonType('pj')}><Building2/> Empresa</button></div>
        <label>{personType==='pf'?'Nome completo':'Responsável pela empresa'}<input name="name" required/></label><label>{personType==='pf'?'CPF':'CNPJ'}<input name="document" inputMode="numeric" required/></label><label>Telefone com DDD<input name="phone" inputMode="tel" required/></label><label>PIN inicial<input name="pin" type="password" inputMode="numeric" pattern="[0-9]{4}" maxLength={4} required/></label>
        {personType==='pj'&&<fieldset className="establishments"><legend>Estabelecimentos e sistemas</legend>{places.map((place,index)=><div className="establishment-row" key={index}><label>Estabelecimento<input value={place.name} onChange={e=>setPlaces(all=>all.map((item,i)=>i===index?{...item,name:e.target.value}:item))} required/></label><label>Sistema<input value={place.system} onChange={e=>setPlaces(all=>all.map((item,i)=>i===index?{...item,system:e.target.value}:item))}/></label><label className="system-url">Link do sistema<input type="url" value={place.url} onChange={e=>setPlaces(all=>all.map((item,i)=>i===index?{...item,url:e.target.value}:item))} placeholder="https://..."/></label>{places.length>1&&<button type="button" className="icon-button danger" onClick={()=>setPlaces(all=>all.filter((_,i)=>i!==index))}><Trash2/></button>}</div>)}<button type="button" className="add-establishment" onClick={()=>setPlaces(all=>[...all,{name:'',system:'',url:''}])}><Plus/> Adicionar estabelecimento</button></fieldset>}
        <button className="button"><Plus/> Cadastrar cliente</button>
      </form>
      <form className="portal-card" onSubmit={e=>submit(e,'charge')}><span className="portal-icon"><CreditCard/></span><h2>Nova cobrança</h2><label>Cliente<select name="clientId" required defaultValue=""><option value="" disabled>Selecione</option>{clients.map(client=><option value={client.id} key={client.id}>{client.name}</option>)}</select></label><label>Descrição<input name="description" required/></label><div className="field-row"><label>Valor (R$)<input name="amount" type="number" min="1" step="0.01" required/></label><label>Vencimento<input name="dueDate" type="date" required/></label></div><button className="button" disabled={!clients.length}><CreditCard/> Emitir cobrança</button></form>
    </div>
    <section className="portal-card admin-client-list"><header><div><span className="kicker">Cadastros</span><h2>Clientes</h2></div></header>{clients.map(client=><article key={client.id}><span><b>{client.name}</b><small>{client.personType==='pj'?`CNPJ · ${client.establishments?.length||0} estabelecimento(s)`:'Pessoa física'} · {client.phone}</small>{client.establishments?.map(place=><small key={place.id}>{place.name}{place.system?` — ${place.system}`:''}{place.url&&<a href={place.url} target="_blank" rel="noreferrer"> Abrir sistema <ExternalLink/></a>}</small>)}</span><button className="icon-button danger" onClick={()=>remove('client',client.id)} aria-label="Excluir cliente"><Trash2/></button></article>)}</section>
    <div className="records-grid"><section className="portal-card admin-client-list"><header><div><span className="kicker">Financeiro</span><h2>Cobranças</h2></div></header>{charges.map(charge=><article key={charge.id}><span><b>{charge.description}</b><small>{clientName(charge.clientId)} · {money(charge.amount)} · {charge.status}</small></span><button className="icon-button danger" onClick={()=>remove('charge',charge.id,charge.clientId)}><Trash2/></button></article>)}{!charges.length&&<p className="portal-empty">Nenhuma cobrança.</p>}</section><section className="portal-card admin-client-list"><header><div><span className="kicker">Atendimento</span><h2>Solicitações</h2></div></header>{requests.map(item=><article key={item.id}><span><b><Wrench/> {item.title}</b><small>{clientName(item.clientId)} · {item.status}</small><small>{item.details}</small></span><button className="icon-button danger" onClick={()=>remove('request',item.id,item.clientId)}><Trash2/></button></article>)}{!requests.length&&<p className="portal-empty">Nenhuma solicitação.</p>}</section></div>
  </section></>;
}
