import { useEffect,useState,type FormEvent } from 'react';
import { ArrowUpRight,CheckCircle2,Clock3,ExternalLink,FileText,Globe2,LogOut,ReceiptText,Send,ShieldCheck,Wrench } from 'lucide-react';
import { Seo } from '../components/Seo';
type Charge={id:string;description:string;amount:number;dueDate:string;status:'pending'|'paid'|'overdue';receiptUrl?:string};
type RequestItem={id:string;title:string;details:string;status:string;createdAt:string};
type Place={id:string;name:string;system:string;url:string};
type PortalData={client:{name:string;personType:'pf'|'pj';establishments:Place[]};charges:Charge[];requests:RequestItem[]};
const money=(cents:number)=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(cents/100);
const date=(value:string)=>new Intl.DateTimeFormat('pt-BR').format(new Date(`${value.slice(0,10)}T12:00:00`));

export default function ClientPortal(){
  const [token,setToken]=useState(()=>sessionStorage.getItem('acs-client-token')||''); const [data,setData]=useState<PortalData|null>(null); const [error,setError]=useState(''); const [loading,setLoading]=useState(false); const [requestOpen,setRequestOpen]=useState(false);
  async function load(activeToken=token){if(!activeToken)return;const response=await fetch('/api/portal/data',{headers:{authorization:`Bearer ${activeToken}`}});if(!response.ok){sessionStorage.removeItem('acs-client-token');setToken('');return}setData(await response.json())}
  // eslint-disable-next-line react-hooks/exhaustive-deps
  useEffect(()=>{void load()},[token]);
  async function login(event:FormEvent<HTMLFormElement>){event.preventDefault();setLoading(true);setError('');const form=new FormData(event.currentTarget);const response=await fetch('/api/portal/login',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({phone:form.get('phone'),pin:form.get('pin')})});const result=await response.json();setLoading(false);if(!response.ok)return setError(result.error||'Não foi possível entrar.');sessionStorage.setItem('acs-client-token',result.token);setToken(result.token)}
  async function checkout(id:string){setLoading(true);const response=await fetch('/api/portal/checkout',{method:'POST',headers:{'content-type':'application/json',authorization:`Bearer ${token}`},body:JSON.stringify({chargeId:id})});const result=await response.json();setLoading(false);if(response.ok&&result.url)window.location.href=result.url;else setError(result.error||'Não foi possível abrir o pagamento.')}
  async function requestService(event:FormEvent<HTMLFormElement>){event.preventDefault();setLoading(true);const form=new FormData(event.currentTarget);const response=await fetch('/api/portal/data',{method:'POST',headers:{'content-type':'application/json',authorization:`Bearer ${token}`},body:JSON.stringify({title:form.get('title'),details:form.get('details')})});setLoading(false);if(response.ok){setRequestOpen(false);await load()}else setError('Não foi possível enviar a solicitação.')}
  if(!token)return <><Seo title="Área do Cliente" description="Acesse cobranças, pagamentos e serviços da ACS Informática."/><section className="client-login"><form className="client-login-card" onSubmit={login}><span className="portal-icon"><ShieldCheck/></span><span className="kicker">Área do Cliente</span><h1>Bem-vindo.</h1><p>Acesse seus sistemas, cobranças, pagamentos e solicitações.</p><label>Telefone com DDD<input name="phone" inputMode="tel" autoComplete="tel" required/></label><label>PIN de 4 dígitos<input name="pin" type="password" inputMode="numeric" pattern="[0-9]{4}" maxLength={4} required/></label>{error&&<p className="form-error">{error}</p>}<button className="button" disabled={loading}>{loading?'Entrando…':'Entrar com segurança'}</button></form></section></>;
  if(!data)return <div className="page-loader">Carregando seus sistemas…</div>;
  return <><Seo title="Meu painel" description="Portal do cliente ACS Informática."/><section className="client-portal">
    <header className="portal-heading"><div><span className="kicker">Área do Cliente</span><h1>Olá, {data?.client.name||'cliente'}.</h1><p>Seus sistemas e serviços da ACS Informática em um só lugar.</p></div><button className="button button-ghost" onClick={()=>{sessionStorage.removeItem('acs-client-token');setToken('');setData(null)}}><LogOut/> Sair</button></header>
    {error&&<p className="form-error">{error}</p>}
    {data?.client.establishments?.length>0&&<section className="client-systems"><div className="client-systems-head"><span className="kicker">Meus sistemas</span><h2>Acesso rápido</h2></div><div className="system-preview-grid">{data.client.establishments.map(place=><article key={place.id}><div className="system-browser"><span className="browser-bar"><i/><i/><i/><small>{place.url||'Sistema ACS'}</small></span>{place.url?<iframe src={place.url} title={`Página inicial de ${place.name}`} loading="lazy" sandbox=""/>:<div className="system-no-preview"><Globe2/><span>Link ainda não informado</span></div>}</div><div className="system-preview-copy"><span><strong>{place.name}</strong><small>{place.system||'Sistema ACS'}</small></span>{place.url&&<a className="button" href={place.url} target="_blank" rel="noreferrer">Acessar sistema <ExternalLink/></a>}</div></article>)}</div></section>}
    <div className="portal-summary"><article><ReceiptText/><span>Em aberto</span><strong>{money(data?.charges.filter(c=>c.status!=='paid').reduce((sum,c)=>sum+c.amount,0)||0)}</strong></article><article><CheckCircle2/><span>Pagamentos</span><strong>{data?.charges.filter(c=>c.status==='paid').length||0}</strong></article><article><Wrench/><span>Solicitações</span><strong>{data?.requests.length||0}</strong></article></div>
    <div className="portal-grid"><section className="portal-card"><header><div><span className="kicker">Financeiro</span><h2>Cobranças</h2></div></header><div className="charge-list">{data?.charges.map(charge=><article key={charge.id}><span className={`charge-status ${charge.status}`}>{charge.status==='paid'?<CheckCircle2/>:<Clock3/>}{charge.status==='paid'?'Pago':charge.status==='overdue'?'Vencido':'Pendente'}</span><div><h3>{charge.description}</h3><small>Vencimento {date(charge.dueDate)}</small></div><strong>{money(charge.amount)}</strong>{charge.status==='paid'&&charge.receiptUrl?<a className="button button-ghost" href={charge.receiptUrl} target="_blank" rel="noreferrer"><FileText/> Comprovante</a>:charge.status!=='paid'&&<button className="button" onClick={()=>checkout(charge.id)} disabled={loading}>Pagar agora <ArrowUpRight/></button>}</article>)}{data&&!data.charges.length&&<p className="portal-empty">Nenhuma cobrança cadastrada.</p>}</div></section><section className="portal-card"><header><div><span className="kicker">Atendimento</span><h2>Serviços</h2></div><button className="button" onClick={()=>setRequestOpen(!requestOpen)}><Send/> Solicitar</button></header>{requestOpen&&<form className="service-request" onSubmit={requestService}><label>Assunto<input name="title" required/></label><label>Descreva sua necessidade<textarea name="details" rows={5} required minLength={10}/></label><button className="button" disabled={loading}>Enviar solicitação</button></form>}<div className="request-list">{data?.requests.map(item=><article key={item.id}><span>{item.status==='received'?'Recebida':item.status}</span><h3>{item.title}</h3><p>{item.details}</p></article>)}{data&&!data.requests.length&&!requestOpen&&<p className="portal-empty">Você ainda não possui solicitações.</p>}</div></section></div>
  </section></>;
}
