import { getStore } from '@netlify/blobs';

export type Establishment = { id:string; name:string; system:string };
export type Client = { id:string; name:string; phone:string; personType:'pf'|'pj'; document:string; establishments:Establishment[]; pinHash:string; salt:string; active:boolean };
export type Charge = { id:string; clientId:string; description:string; amount:number; dueDate:string; status:'pending'|'paid'|'overdue'; createdAt:string; transactionNsu?:string; receiptUrl?:string; captureMethod?:string };
export type ServiceRequest = { id:string; clientId:string; title:string; details:string; status:'received'|'reviewing'|'approved'|'completed'; createdAt:string };
export const store = getStore({name:'acs-client-portal',consistency:'strong'});
export const json = (data:unknown,status=200,headers:Record<string,string>={}) => new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json; charset=utf-8',...headers}});
export const normalizePhone=(value:string)=>value.replace(/\D/g,'');
const encode=(data:Uint8Array|string)=>Buffer.from(data).toString('base64url');
const secret=()=>Netlify.env.get('PORTAL_SESSION_SECRET')||'';
export async function hashPin(pin:string,salt:string){const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(pin),'PBKDF2',false,['deriveBits']);const bits=await crypto.subtle.deriveBits({name:'PBKDF2',hash:'SHA-256',salt:new TextEncoder().encode(salt),iterations:120000},key,256);return encode(new Uint8Array(bits))}
export async function tokenFor(client:Client){const body=encode(JSON.stringify({sub:client.id,name:client.name,exp:Date.now()+8*60*60*1000}));const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(secret()),{name:'HMAC',hash:'SHA-256'},false,['sign']);const sig=await crypto.subtle.sign('HMAC',key,new TextEncoder().encode(body));return `${body}.${encode(new Uint8Array(sig))}`}
export async function authenticate(req:Request){const token=req.headers.get('authorization')?.replace(/^Bearer /,'');if(!token||!secret())return null;const [body,sig]=token.split('.');if(!body||!sig)return null;const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(secret()),{name:'HMAC',hash:'SHA-256'},false,['verify']);const valid=await crypto.subtle.verify('HMAC',key,Buffer.from(sig,'base64url'),new TextEncoder().encode(body));if(!valid)return null;const payload=JSON.parse(Buffer.from(body,'base64url').toString()) as {sub:string;name:string;exp:number};return payload.exp>Date.now()?payload:null}
export async function listJSON<T>(prefix:string){const {blobs}=await store.list({prefix});return Promise.all(blobs.map(blob=>store.get(blob.key,{type:'json'}) as Promise<T>))}
export async function adminAllowed(req:Request){const expected=Netlify.env.get('ADMIN_API_SECRET');if(expected&&req.headers.get('x-admin-secret')===expected)return true;const cookie=req.headers.get('cookie')?.split(';').map(value=>value.trim()).find(value=>value.startsWith('acs_admin_session='))?.split('=')[1];if(!cookie||!secret())return false;const [body,sig]=cookie.split('.');if(!body||!sig)return false;const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(secret()),{name:'HMAC',hash:'SHA-256'},false,['verify']);const valid=await crypto.subtle.verify('HMAC',key,Buffer.from(sig,'base64url'),new TextEncoder().encode(body));if(!valid)return false;const payload=JSON.parse(Buffer.from(body,'base64url').toString()) as {role:string;exp:number};return payload.role==='admin'&&payload.exp>Date.now()}
export async function adminSession(){const body=encode(JSON.stringify({role:'admin',exp:Date.now()+7*24*60*60*1000}));const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(secret()),{name:'HMAC',hash:'SHA-256'},false,['sign']);const sig=await crypto.subtle.sign('HMAC',key,new TextEncoder().encode(body));return `${body}.${encode(new Uint8Array(sig))}`}
